apiVersion: v1
kind: Secret
metadata:
  name: heycloud-db-secret
  labels:
    app: heycloud-app
type: Opaque
data:
  DB_USER: aGFyaXNo        # base64 for "harish"
  DB_PASSWORD: aGFyaXNoMTIzNA==  # base64 for "harish1234"
  ROOT_PASSWORD: cm9vdA==        # base64 for "root"
